// This file was generated by img2gb, DO NOT EDIT

#ifndef _TILESET_H
#define _TILESET_H

extern const UINT8 TILESET[];
#define TILESET_TILE_COUNT 5

// Tile count of player.
#define PLAYER_TILESET_TILE_COUNT 3


#endif
